apiVersion: apps/v1
kind: Deployment
metadata:
  name: togeojson
  namespace: pt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: togeojson
  template:
    metadata:
      labels:
        app: togeojson
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics.portName: "http"
        k8s.grafana.com/job: "togeojson-server"
    spec:
      containers:
        - name: togeojson
          image: ghcr.io/dzfranklin/togeojson-server:latest
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: http
